# Generated by Django 4.2.2 on 2023-07-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicproapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='a', max_length=1000, verbose_name='Descripción del Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Tipo de producto'),
        ),
    ]
