# Generated by Django 4.2.2 on 2023-07-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicproapp', '0003_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=1000, verbose_name='Descripción del Producto'),
        ),
    ]
