# Generated by Django 4.2.2 on 2023-07-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicproapp', '0004_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
