# Generated by Django 4.2.2 on 2023-07-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicproapp', '0005_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('codigo_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_productos', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
