# Generated by Django 4.2.2 on 2023-07-12 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicproapp', '0006_boleta_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='boleta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicproapp.boleta'),
            preserve_default=False,
        ),
    ]
