# Generated by Django 4.1 on 2023-07-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicproapp', '0007_compras_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
