# Generated by Django 4.2.2 on 2023-07-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicproapp', '0009_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado del Producto'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='productos'),
        ),
    ]
