# Generated by Django 4.2.2 on 2023-07-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicproapp', '0010_alter_boleta_estado_alter_perfil_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='fecha',
            field=models.DateField(default="2023-01-01"),
            preserve_default=False,
        ),
    ]
