# Generated by Django 4.2.2 on 2023-07-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicproapp', '0011_boleta_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrega',
        ),
    ]
