# Generated by Django 4.2.2 on 2023-07-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicproapp', '0013_entrega_alter_boleta_estado_vendedor_contador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado del producto'),
        ),
    ]
